const data = [
  {
    "product_id": 1,
    "product_name": "Floral Magenta Teacup",
    "product_desc": "Elegant teacup with a floral magenta design.",
    "product_price": "259.89",
    "product_stock": 50,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-teacups-floral-magenta.jpg",
    "product_rating": "4.7",
    "category_id": 7,
    "ordered_from": "Kopii Shop"
  },
  {
    "product_id": 4,
    "product_name": "Fuchsia Teacup",
    "product_desc": "Stylish fuchsia teacup for a delightful tea experience.",
    "product_price": "289.90",
    "product_stock": 25,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-teacups-fushcia.jpg",
    "product_rating": "4.8",
    "category_id": 7,
    "ordered_from": "Kopii Shop"
  },
  {
    "product_id": 5,
    "product_name": "Pure White Teacup",
    "product_desc": "Simple and pure white teacup for a minimalist touch.",
    "product_price": "345.90",
    "product_stock": 43,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-teacups-porcelain-white.jpg",
    "product_rating": "4.1",
    "category_id": 7,
    "ordered_from": "Kopii Shop"
  },
  {
    "product_id": 6,
    "product_name": "Tea Set",
    "product_desc": "Complete tea set for a delightful tea party experience.",
    "product_price": "1100.90",
    "product_stock": 55,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-teacups-tea-set.jpg",
    "product_rating": "4.8",
    "category_id": 7,
    "ordered_from": "Kopii Shop"
  },
  {
    "product_id": 7,
    "product_name": "White Teacup",
    "product_desc": "Simple and elegant white teacup for everyday use.",
    "product_price": "512.59",
    "product_stock": 55,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-teacups-white.jpg",
    "product_rating": "4.2",
    "category_id": 7,
    "ordered_from": "Kopii Shop"
  },
  {
    "product_id": 8,
    "product_name": "Porcelain White Teacup",
    "product_desc": "Classic porcelain white teacup for timeless elegance.",
    "product_price": "512.59",
    "product_stock": 55,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-teacups-porcelain-white.jpg",
    "product_rating": "4.7",
    "category_id": 7,
    "ordered_from": "Kopii Shop"
  },
  {
    "product_id": 9,
    "product_name": "Croissant",
    "product_desc": "Classic and flaky croissant for a delightful breakfast.",
    "product_price": "125.90",
    "product_stock": 78,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-pastries-croissant.jpg",
    "product_rating": "4.9",
    "category_id": 2,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 10,
    "product_name": "Assorted Donuts",
    "product_desc": "A variety pack of delicious and colorful donuts.",
    "product_price": "459.89",
    "product_stock": 102,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-pastries-donuts.jpg",
    "product_rating": "4.3",
    "category_id": 2,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 11,
    "product_name": "Easter Slice Pastry",
    "product_desc": "Special pastry slice with Easter-themed decorations.",
    "product_price": "410.90",
    "product_stock": 60,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-pastries-easter-slice.jpg",
    "product_rating": "4.9",
    "category_id": 2,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 12,
    "product_name": "Homemade Pastry",
    "product_desc": "Freshly baked homemade pastry for a comforting treat.",
    "product_price": "299.99",
    "product_stock": 75,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-pastries-homemade.jpg",
    "product_rating": "4.5",
    "category_id": 2,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 13,
    "product_name": "Original Croissant",
    "product_desc": " The original classic croissant for a buttery taste.",
    "product_price": "156.79",
    "product_stock": 90,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-pastries-original-croissant.jpg",
    "product_rating": "4.6",
    "category_id": 2,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 14,
    "product_name": "Sprinkled Donuts",
    "product_desc": "Donuts topped with colorful sprinkles for a fun twist.",
    "product_price": "530.00",
    "product_stock": 85,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-pastries-homemade.jpg",
    "product_rating": "4.9",
    "category_id": 2,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 15,
    "product_name": "Vanilla Classic Pastry",
    "product_desc": "Classic pastry with a delightful vanilla flavor.",
    "product_price": "312.70",
    "product_stock": 30,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-pastries-vanilla-classic.jpg",
    "product_rating": "4.8",
    "category_id": 2,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 16,
    "product_name": "Creulen Cup",
    "product_desc": "Elegant cerulean tea cup for a sophisticated tea experience.",
    "product_price": "3428.90",
    "product_stock": 13,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-teacups-cerulean-cup.jpg",
    "product_rating": "4.6",
    "category_id": 7,
    "ordered_from": "Kopii Shop"
  },
  {
    "product_id": 17,
    "product_name": "Dark Grey Teacup",
    "product_desc": " Stylish dark grey teacup for a modern touch.",
    "product_price": "3300.70",
    "product_stock": 56,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-teacups-dark-grey.jpg",
    "product_rating": "4.5",
    "category_id": 7,
    "ordered_from": "Kopii Shop"
  },
  {
    "product_id": 18,
    "product_name": "Dark Velvet Teacup",
    "product_desc": "Luxurious dark velvet teacup for a rich tea experience.",
    "product_price": "4428.90",
    "product_stock": 13,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-teacups-dark-velvet.jpg",
    "product_rating": "4.9",
    "category_id": 7,
    "ordered_from": "Kopii Shop"
  },
  {
    "product_id": 19,
    "product_name": "Chocolate Bar",
    "product_desc": "Indulge in the rich and smooth taste of our assorted chocolate bar.",
    "product_price": "270.70",
    "product_stock": 59,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-chocolates-bar.jpg",
    "product_rating": "4.9",
    "category_id": 9,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 20,
    "product_name": "Fruit Pancake",
    "product_desc": "Start your day with a delightful fruit pancake for a burst of flavors.",
    "product_price": "238.90",
    "product_stock": 69,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-breakfast-fruit-pancake.jpg",
    "product_rating": "4.9",
    "category_id": 10,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 21,
    "product_name": "Bread Slice",
    "product_desc": "Classic bread slice for a simple and satisfying breakfast.",
    "product_price": "135.70",
    "product_stock": 13,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-breakfast-bread-slice.jpg",
    "product_rating": "4.5",
    "category_id": 10,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 22,
    "product_name": "Pine Tree Biscuits",
    "product_desc": "Unique pine tree-shaped biscuits for a festive treat.",
    "product_price": "267.90",
    "product_stock": 69,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-biscuits-pine-tree-biscuits.jpg",
    "product_rating": "4.2",
    "category_id": 3,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 23,
    "product_name": "Original Biscuits",
    "product_desc": "Classic and buttery original biscuits for a timeless snack.",
    "product_price": "190.40",
    "product_stock": 63,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-biscuits-original-biscuits.jpg",
    "product_rating": "4.7",
    "category_id": 3,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 24,
    "product_name": "Jarred Biscuits",
    "product_desc": "Biscuits sealed in a jar for freshness and convenience.",
    "product_price": "447.90",
    "product_stock": 49,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-biscuits-jarred-biscuits.jpg",
    "product_rating": "4.7",
    "category_id": 3,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 25,
    "product_name": "Assorted Chocolate Bites",
    "product_desc": "Enjoy a variety of chocolate bites for a delightful experience.",
    "product_price": "348.40",
    "product_stock": 43,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/categories-chocolates-assorted-bites.jpg",
    "product_rating": "4.8",
    "category_id": 9,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 26,
    "product_name": "Boxed Classic Chocolates",
    "product_desc": "A classic assortment of chocolates in an elegant box.",
    "product_price": "678.90",
    "product_stock": 89,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-chocolates-boxed-classic.jpg",
    "product_rating": "4.5",
    "category_id": 9,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 27,
    "product_name": "Spinach Carb-Free Chocolates",
    "product_desc": "Unique carb-free chocolates infused with spinach for a healthy twist.",
    "product_price": "566.40",
    "product_stock": 43,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-chocolates-spinach-carb-free.jpg",
    "product_rating": "5.0",
    "category_id": 9,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 28,
    "product_name": "Dark Chocolates",
    "product_desc": "Indulge in the intense and bold flavor of our dark chocolate.",
    "product_price": "200.90",
    "product_stock": 89,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-chocolates-dark.jpg",
    "product_rating": "4.3",
    "category_id": 9,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 29,
    "product_name": "Nutella Special Package Chocolates",
    "product_desc": "Indulge in the heavenly combination of Nutella and premium chocolates.",
    "product_price": "1980.40",
    "product_stock": 73,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-chocolates-nutella-special-package.jpg",
    "product_rating": "4.9",
    "category_id": 9,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 30,
    "product_name": "Easter Egg Variant Chocolates",
    "product_desc": "Celebrate Easter with our delightful egg-shaped chocolates in various flavors.\n",
    "product_price": "451.90",
    "product_stock": 59,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-chocolates-easter-egg-variant.jpg",
    "product_rating": "4.7",
    "category_id": 9,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 31,
    "product_name": "Chocolate Cupcake",
    "product_desc": "Savor the sweetness of our delectable chocolate cupcake for a delightful treat.",
    "product_price": "580.40",
    "product_stock": 73,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-chocolates-chocolate-cupcake.jpg",
    "product_rating": "4.4",
    "category_id": 9,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 32,
    "product_name": "Classic Cocoa Chocolates",
    "product_desc": "Enjoy the classic and rich taste of cocoa in every bite of our chocolates.",
    "product_price": "870.90",
    "product_stock": 59,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-chocolates-calssic-cocoa.jpg",
    "product_rating": "4.9",
    "category_id": 9,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 33,
    "product_name": "Boxed Classic Chocolates",
    "product_desc": "A timeless assortment of chocolates in an exquisite boxed collection.",
    "product_price": "980.40",
    "product_stock": 73,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-chocolates-boxed-classic.jpg",
    "product_rating": "5.0",
    "category_id": 9,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 34,
    "product_name": "Valentine's Chocolates",
    "product_desc": "Express your love with our specially crafted Valentine's Day chocolates.",
    "product_price": "470.90",
    "product_stock": 59,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-chocolates-valentines.jpg",
    "product_rating": "4.5",
    "category_id": 9,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 35,
    "product_name": "Artisan Coffee Beans",
    "product_desc": "Experience the rich and bold flavors of our carefully selected artisan coffee beans.",
    "product_price": "1880.40",
    "product_stock": 73,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-coffee-beans-artisan.jpg",
    "product_rating": "4.9",
    "category_id": 1,
    "ordered_from": "Kopii Shop"
  },
  {
    "product_id": 36,
    "product_name": "Gourmet Coffee Beans",
    "product_desc": "Elevate your coffee experience with our premium selection of gourmet coffee beans.",
    "product_price": "1470.90",
    "product_stock": 59,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-coffee-beans--gourmet.jpg",
    "product_rating": "4.8",
    "category_id": 1,
    "ordered_from": "Kopii Shop"
  },
  {
    "product_id": 37,
    "product_name": "Curated Coffee Beans",
    "product_desc": "A curated blend of coffee beans for a well-balanced and aromatic cup.",
    "product_price": "1124.40",
    "product_stock": 73,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-coffee-beans-curated.jpg",
    "product_rating": "4.4",
    "category_id": 1,
    "ordered_from": "Kopii Shop"
  },
  {
    "product_id": 38,
    "product_name": "Specialty Coffee Beans",
    "product_desc": "Discover the unique and distinctive flavors of our specialty coffee beans.",
    "product_price": "1660.90",
    "product_stock": 59,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-coffee-beans-specialty.jpg",
    "product_rating": "4.5",
    "category_id": 1,
    "ordered_from": "Kopii Shop"
  },
  {
    "product_id": 39,
    "product_name": "Christmas Variation Cookies",
    "product_desc": "Delight in the festive spirit with our Christmas-themed assortment of cookies.",
    "product_price": "824.40",
    "product_stock": 75,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-cookies-christmas-variation.jpg",
    "product_rating": "5.0",
    "category_id": 5,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 40,
    "product_name": "Classic Cookies",
    "product_desc": "Experience the timeless taste of our classic and comforting cookies.",
    "product_price": "560.90",
    "product_stock": 59,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-cookies-classic-cookies.jpg",
    "product_rating": "4.7",
    "category_id": 5,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 41,
    "product_name": "Dark Chocolate Cookies",
    "product_desc": " Indulge in the rich and decadent flavors of our dark chocolate-infused cookies.",
    "product_price": "890.40",
    "product_stock": 75,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-cookies-dark-chocolate-cookies.jpg",
    "product_rating": "4.7",
    "category_id": 5,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 42,
    "product_name": "Easter Set Cookies",
    "product_desc": "Celebrate Easter with our specially curated set of delightful cookies.",
    "product_price": "750.40",
    "product_stock": 59,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-cookies-easter-set.jpg",
    "product_rating": "4.9",
    "category_id": 5,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 43,
    "product_name": "Halloween Variation Cookies",
    "product_desc": "Embrace the spooky season with our Halloween-themed variation of cookies.",
    "product_price": "1090.40",
    "product_stock": 75,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-cookies-halloween-variation.jpg",
    "product_rating": "4.8",
    "category_id": 5,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 44,
    "product_name": "Homemade Cookies",
    "product_desc": "Experience the warmth of homemade goodness with our delightful cookies.",
    "product_price": "550.30",
    "product_stock": 59,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-cookies-homemade-cookies.jpg",
    "product_rating": "5.0",
    "category_id": 5,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 45,
    "product_name": "Halloween Variation Cookies",
    "product_desc": "Indulge in luxury with our premium collection of exquisite and flavorful cookies.",
    "product_price": "1990.40",
    "product_stock": 47,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-cookies-premium-cookies.jpg",
    "product_rating": "4.9",
    "category_id": 5,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 46,
    "product_name": "Santa Variation Cookies",
    "product_desc": "Spread holiday cheer with our Santa-themed variation of delicious cookies.",
    "product_price": "450.30",
    "product_stock": 59,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-cookies-santa-variation.jpg",
    "product_rating": "4.4",
    "category_id": 5,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 47,
    "product_name": "Winter Variation Cookies",
    "product_desc": "Embrace the winter season with our special variation of delightful cookies.",
    "product_price": "690.40",
    "product_stock": 47,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-cookies-winter-variation.jpg",
    "product_rating": "4.6",
    "category_id": 5,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 48,
    "product_name": "Assorted Brownies",
    "product_desc": "Indulge your senses with our assorted brownies, perfect for any sweet craving.",
    "product_price": "450.30",
    "product_stock": 59,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-desserts-assorted-brownies.jpg",
    "product_rating": "4.5",
    "category_id": 4,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 49,
    "product_name": "Banana Split Dessert",
    "product_desc": "Indulge in the tropical delight of our Banana Split dessert, perfect for a sweet escape.",
    "product_price": "990.80",
    "product_stock": 47,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-desserts-banana-split.jpg",
    "product_rating": "4.9",
    "category_id": 4,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 50,
    "product_name": "Black Berry Slice",
    "product_desc": "Experience the rich and fruity flavors with our delectable Black Berry Slice dessert.",
    "product_price": "450.30",
    "product_stock": 59,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-desserts-black-berry-slice.jpg",
    "product_rating": "4.9",
    "category_id": 4,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 51,
    "product_name": "Coffee Mint Slice",
    "product_desc": "Elevate your taste buds with the refreshing blend of coffee and mint in our delightful slice.",
    "product_price": "1040.99",
    "product_stock": 47,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-desserts-coffee-mint-slice.jpg",
    "product_rating": "4.8",
    "category_id": 4,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 52,
    "product_name": "Cream Cake Slice",
    "product_desc": " Indulge in the velvety smoothness of our Cream Cake Slice, a true treat for dessert lovers.",
    "product_price": "950.99",
    "product_stock": 59,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-desserts-cream-cake-slice.jpg",
    "product_rating": "4.9",
    "category_id": 4,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 53,
    "product_name": "Macaron",
    "product_desc": "Experience the delicate and delightful taste of our perfectly crafted Macarons.",
    "product_price": "1440.99",
    "product_stock": 47,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-desserts-macaron.jpg",
    "product_rating": "4.8",
    "category_id": 4,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 54,
    "product_name": "Red Cake Slice",
    "product_desc": "Savor the luxurious flavors of our Red Velvet Slice, a decadent dessert experience.",
    "product_price": "980.99",
    "product_stock": 59,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-desserts-red-velvet-slice.jpg",
    "product_rating": "4.7",
    "category_id": 4,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 55,
    "product_name": "Vanilla Cream Slice",
    "product_desc": "Delight in the classic elegance of our Vanilla Cream Slice, a timeless dessert choice.",
    "product_price": "1140.99",
    "product_stock": 47,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-desserts-vanilla-cream-slice.jpg",
    "product_rating": "4.5",
    "category_id": 4,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 56,
    "product_name": "Vanilla Orchard Slice",
    "product_desc": "Immerse yourself in the orchard-fresh goodness of our Vanilla Orchard Slice.",
    "product_price": "940.99",
    "product_stock": 59,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-desserts-vanilla-orchard-slice.jpg",
    "product_rating": "4.9",
    "category_id": 4,
    "ordered_from": "Kopii Stop"
  },
  {
    "product_id": 57,
    "product_name": "Tote Bag (Black)",
    "product_desc": "Carry your essentials in style with our chic and versatile black tote bag.",
    "product_price": "1940.99",
    "product_stock": 49,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-merchandise-tote-bag-black.jpg",
    "product_rating": "4.9",
    "category_id": 6,
    "ordered_from": "Kopii Shop"
  },
  {
    "product_id": 58,
    "product_name": "Totw Bag (Brown)",
    "product_desc": "Embrace sophistication with our brown tote bag, a perfect blend of fashion and functionality.",
    "product_price": "940.99",
    "product_stock": 99,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-merchandise-tote-bag-brown.jpg",
    "product_rating": "4.9",
    "category_id": 6,
    "ordered_from": "Kopii Shop"
  },
  {
    "product_id": 59,
    "product_name": "Animal Land Mugs",
    "product_desc": "Explore the whimsical world of animals with our charming Animal Land mugs.",
    "product_price": "1540.99",
    "product_stock": 49,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-mugs-animal-land.jpg",
    "product_rating": "5.0",
    "category_id": 8,
    "ordered_from": "Kopii Shop"
  },
  {
    "product_id": 60,
    "product_name": "Beast & Beauty Mugs",
    "product_desc": "Unleash your inner beauty with our Beast Beauty mugs, a perfect blend of strength and grace.\n",
    "product_price": "940.99",
    "product_stock": 63,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-mugs-beast-beauty-mugs.jpg",
    "product_rating": "4.9",
    "category_id": 8,
    "ordered_from": "Kopii Shop"
  },
  {
    "product_id": 61,
    "product_name": "Canvas Mugs",
    "product_desc": "Elevate your sipping experience with our sophisticated Canvas mugs.",
    "product_price": "1440.99",
    "product_stock": 69,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-mugs-canvas.jpg",
    "product_rating": "4.0",
    "category_id": 8,
    "ordered_from": "Kopii Shop"
  },
  {
    "product_id": 62,
    "product_name": "Choose Happy Mugs",
    "product_desc": "Start your day on a positive note with our uplifting Choose Happy mugs.",
    "product_price": "940.99",
    "product_stock": 63,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-mugs-choose-happy.jpg",
    "product_rating": "4.9",
    "category_id": 8,
    "ordered_from": "Kopii Shop"
  },
  {
    "product_id": 63,
    "product_name": "Dark Brown Simple Mug",
    "product_desc": "Embrace simplicity with our Dark Brown Simple mug, a perfect companion for your favorite beverages.",
    "product_price": "440.99",
    "product_stock": 69,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-mugs-dark-brown-simple-mug.jpg",
    "product_rating": "4.9",
    "category_id": 8,
    "ordered_from": "Kopii Shop"
  },
  {
    "product_id": 64,
    "product_name": "ILY Mugs",
    "product_desc": "Express your love with our charming Ily mugs, a heartfelt addition to your collection.",
    "product_price": "980.99",
    "product_stock": 167,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-mugs-ily-mugs.jpg",
    "product_rating": "4.5",
    "category_id": 8,
    "ordered_from": "Kopii Shop"
  },
  {
    "product_id": 65,
    "product_name": "Pair of Mugs",
    "product_desc": "Share moments and beverages with our delightful Pair of Mugs, a perfect gift for loved ones.",
    "product_price": "499.99",
    "product_stock": 69,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-mugs-pair-of-mugs.jpg",
    "product_rating": "4.6",
    "category_id": 8,
    "ordered_from": "Kopii Shop"
  },
  {
    "product_id": 66,
    "product_name": "Plain White Mugs",
    "product_desc": "Embrace simplicity with our Plain White mugs, a versatile choice for any occasion.",
    "product_price": "780.99",
    "product_stock": 16,
    "product_img": "https://kopiiiiiimg.netlify.app/assets/images/category-mugs-plain-white.jpg",
    "product_rating": "4.9",
    "category_id": 8,
    "ordered_from": "Kopii Shop"
  }
]